### ISSUE TITLE
make eps an option and use upsampfac=1.25

### ISSUE THREAD

**Issue by ahbarnett** [gauteh/fsinc#1]
Dear Gaute,
Nice work with this package!
Two suggestions to get a lot more speed:
1) make eps a user argument, with a default of 1e-6, say. (No-one really needs 1e-15, and the speed-up will be a factor of several. For such interpolation problems 1e-3 to 1e-6 is fine).
2) always call your type 3 nufft's with upsampfac=1.25. Usually this is faster than the default, esp in 2d or 3d.

We're working on v1.2 of FINUFFT right now, but will try to keep the py package bkw-compatible.
I let Hannah know about your repo.
Best wishes,  Alex

**Comment by gauteh** [comment]
Dear Alex,

Thank you very much. Thanks for the good suggestions. I put in some
benchmarks prompted by your comment and found another weird performance
difference; sinc2d^2 is much faster than sinc2d. Might be related to
amplitude of numbers or memory/cache misses when generating GL nodes. I
will test out your suggestions as well. At the moment much of the time
is spent generating GL nodes.

Thanks for the heads up about the new version on FINUFFT, this package
is so young that it will not be a problem to update to a new API once it
is ready. I briefly corresponded with Hannah already, this package is
heavily based on her work.

By the way; the interpolation in 2d using jacobian weighting does not
really work. I have not figured out a good way to approximate it for
arbitrary sample locations. The sinc^2 weighting works fine, but in 1d
the jacobian weighting seems to be a bit more robust -- though it may be
less correct.

Best regards, Gaute

Alex Barnett writes on May 30, 2020 4:12:

**Comment by ahbarnett** [comment]
Great. I wonder how much faster the nufft calls are now?

I forgot to add that upsampfac=1.25 will bottom out at around 1e-9. If the user insists on eps smaller than that you could switch to upsampfac=2.

Gauss quadrature computation should be much cheaper than the nuffts. Here's why. The number of nodes is asymptotically linear in the number of wavelengths (of the sinc) across the spatial domain, so it could get large, 1e3 or 1e4, say. Regardless, even in 1D, the number of freq nodes will be less than M, the # spatial nodes (otherwise you're trying to interpolate with >1 wavelength between points!).

We know Bogaert's code gets 1e7 nodes/sec, even single-core:
http://pi.math.cornell.edu/~ajt/papers/QuadratureEssay.pdf

That is around FINUFFT speed, showing that node generation should not dominate.

So, maybe Burkardt's implementation isn't so good? I would just wrap the original C in py.

But, you can bypass this whole issue (and reduce the # nodes by an asymptotic factor pi/2) by using Alpert's high-order end corrections to the trapezoid rule. Almost all the nodes are equispaced then (even enabling type 1 & 2 to be used, not type 3, although with upsampfac=1.25 this won't be a big win).

Have fun, Alex

**Comment by gauteh** [comment]
Wow, thanks, I'll check that out! Thanks for the further hints, might be doing some extra work there. I got maybe 20% speedup when doing some quick tests (on up to 2e6 points), but they are not so consistent across runs, so it seems like my environment is not so fair between tests. Trapezoid-rule + corrections is probably sufficient for me. I also got a core dump in numba / fastgl so that's another argument for trying a different approach there.

**Comment by ahbarnett** [comment]
Here's matlab code for Alpert end-corrected trapezoid rule - pick the "smooth" endpoint case and look in that directory for test codes:
https://github.com/ahbarnett/mpspack/blob/master/%40quadr/QuadNodesInterval.m
https://github.com/ahbarnett/mpspack/blob/master/%40quadr/QuadSmoothExtraPtNodes.m
Best, Alex

**Comment by gauteh** [comment]
Alex Barnett writes on May 31, 2020 20:05:
> Here's matlab code for Alpert end-corrected trapezoid rule - pick the "smooth" endpoint case and look in that directory for test codes:
> https://github.com/ahbarnett/mpspack/blob/master/%40quadr/QuadNodesInterval.m
> https://github.com/ahbarnett/mpspack/blob/master/%40quadr/QuadSmoothExtraPtNodes.m
> Best, Alex

Great, thanks!
